# FITS Header keywords (Customize based on your telescope/camera)
fits_keywords:
  ra_key: "OBJCTRA"
  dec_key: "OBJCTDEC"
  date_key: "DATE-OBS"
  exposure_key: "EXPTIME"

# Astrometry parameters
astrometry:
  radius: 0.5
  quad_scales: [0, 2, 4, 6]
  cache_tolerance: 0.1

# Instrument parameters
instrument:
  pixel_scale: 0.62
  gain: 0.57
  read_noise: 4.11
  saturation_level: 50000  # ADU value where the sensor becomes non-linear

observatory:
  observatory_code: "A84"

# DAOStarFinder parameters
source_detection:
  fwhm_guess: 5.0          # Initial FWHM guess for DAOStarFinder
  threshold_sigma: 1.3    # Threshold for detection (multiplier of background std)
  min_area: 5              # Minimum connected pixels for a source
  edge_margin: 10          # Minimum distance from image edges in pixels

# Gaia and target matchhing parameters
matching:
  isolation_radius_arcsec: 0.2  # Min distance to the nearest neighbor (arcsec)
  match_constraint_arcsec: 1.0  # Max distance for Gaia-to-Image matching

# Photometry parameters
photometry:
  mode: "asteroid"       # Options: "asteroid" or "star"
  target_id: "19184"    # Asteroid number or name. Use if mode is "asteroid"
  coords: [124.756279, 16.294038] # Use if mode is "star" type in degrees
  filter: "R"  # Options: B, V, R, I, g, r, i, z
  aperture_method: "fixed_arcsec" # Options: "fixed_pixel", "fixed_arcsec", "fwhm_factor"
  aperture: 4 # Pixel
  annulus_inner: 7   # Annulus
  annulus_outer: 9   # Dannulus
  zeropoint: "fit" #average or fit

# Directories
paths:
  input_dir: "A" #"20260223/test_peno2/test"
  temp_dir: "data/temp"
  index_dir: "data/indexes"
  solve_dir: "output"
  output_photometry: "test.csv" # File name which will be saved as outputs
  output_astrometry: "residuals.csv" # File name which will be saved as outputs
  file_extension: "fits" # File name which will be saved as outputs

plots:
  plot_astrometry: True #True or False
  plot_image: True #True or False
  image_scale: "pixel" # pixel or wcs. Use this if plot image is true

# Catalog settings
catalog: "gaiadr3.gaia_source"

